# Generated by Django 2.2 on 2019-04-25 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20190424_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(null=True, related_name='post_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
